<?php

namespace Proxies\__CG__\Saba\FarmaciaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Medico extends \Saba\FarmaciaBundle\Entity\Medico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'cedula', 'apellidoPaterno', 'apellidoMaterno', 'nombresDePila', 'centroDeCostos', 'especialidad');
        }

        return array('__isInitialized__', 'id', 'cedula', 'apellidoPaterno', 'apellidoMaterno', 'nombresDePila', 'centroDeCostos', 'especialidad');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Medico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedula($cedula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedula', array($cedula));

        return parent::setCedula($cedula);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedula', array());

        return parent::getCedula();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoPaterno($apellidoPaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoPaterno', array($apellidoPaterno));

        return parent::setApellidoPaterno($apellidoPaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoPaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoPaterno', array());

        return parent::getApellidoPaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidoMaterno($apellidoMaterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidoMaterno', array($apellidoMaterno));

        return parent::setApellidoMaterno($apellidoMaterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidoMaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidoMaterno', array());

        return parent::getApellidoMaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombresDePila($nombresDePila)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombresDePila', array($nombresDePila));

        return parent::setNombresDePila($nombresDePila);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombresDePila()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombresDePila', array());

        return parent::getNombresDePila();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentroDeCostos($centroDeCostos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentroDeCostos', array($centroDeCostos));

        return parent::setCentroDeCostos($centroDeCostos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentroDeCostos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentroDeCostos', array());

        return parent::getCentroDeCostos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspecialidad($especialidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspecialidad', array($especialidad));

        return parent::setEspecialidad($especialidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspecialidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspecialidad', array());

        return parent::getEspecialidad();
    }

}
