<?php

namespace Proxies\__CG__\Saba\FarmaciaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Receta extends \Saba\FarmaciaBundle\Entity\Receta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'folio', 'recetaPadre', 'recetasHijas', 'medico', 'paciente', 'lineasDeReceta');
        }

        return array('__isInitialized__', 'id', 'folio', 'recetaPadre', 'recetasHijas', 'medico', 'paciente', 'lineasDeReceta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Receta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFolio($folio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFolio', array($folio));

        return parent::setFolio($folio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFolio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolio', array());

        return parent::getFolio();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecetaPadre($recetaPadre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecetaPadre', array($recetaPadre));

        return parent::setRecetaPadre($recetaPadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecetaPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecetaPadre', array());

        return parent::getRecetaPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function addRecetasHija(\Saba\FarmaciaBundle\Entity\Receta $recetasHijas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecetasHija', array($recetasHijas));

        return parent::addRecetasHija($recetasHijas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecetasHija(\Saba\FarmaciaBundle\Entity\Receta $recetasHijas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecetasHija', array($recetasHijas));

        return parent::removeRecetasHija($recetasHijas);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecetasHijas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecetasHijas', array());

        return parent::getRecetasHijas();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedico(\Saba\FarmaciaBundle\Entity\Medico $medico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedico', array($medico));

        return parent::setMedico($medico);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedico', array());

        return parent::getMedico();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaciente(\Saba\FarmaciaBundle\Entity\Paciente $paciente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaciente', array($paciente));

        return parent::setPaciente($paciente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaciente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaciente', array());

        return parent::getPaciente();
    }

    /**
     * {@inheritDoc}
     */
    public function addLineasDeRecetum(\Saba\FarmaciaBundle\Entity\RecetaTieneLineas $lineaDeReceta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLineasDeRecetum', array($lineaDeReceta));

        return parent::addLineasDeRecetum($lineaDeReceta);
    }

    /**
     * {@inheritDoc}
     */
    public function addLineasDeReceta($lineaDeReceta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLineasDeReceta', array($lineaDeReceta));

        return parent::addLineasDeReceta($lineaDeReceta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLineasDeRecetum(\Saba\FarmaciaBundle\Entity\RecetaTieneLineas $lineasDeReceta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLineasDeRecetum', array($lineasDeReceta));

        return parent::removeLineasDeRecetum($lineasDeReceta);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineasDeReceta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineasDeReceta', array());

        return parent::getLineasDeReceta();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineasDeReceta($lineasDeReceta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineasDeReceta', array($lineasDeReceta));

        return parent::setLineasDeReceta($lineasDeReceta);
    }

}
